apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
data:
  # Notification templates
  template.app-deployed: |
    email:
      subject: 🚀 Application {{.app.metadata.name}} deployed successfully
    message: |
      🎉 **Deployment Successful!**
      
      **Application:** {{.app.metadata.name}}
      **Environment:** {{.app.metadata.labels.environment}}
      **Revision:** {{.app.status.sync.revision}}
      **Sync Status:** {{.app.status.sync.status}}
      **Health Status:** {{.app.status.health.status}}
      
      **Links:**
      - [ArgoCD App]({{.context.argocdUrl}}/applications/{{.app.metadata.name}})
      - [GitHub Commit](https://github.com/tamngo179/BT-PTUDDN/commit/{{.app.status.sync.revision}})
      
      Time: {{.app.status.operationState.finishedAt}}
    slack:
      attachments: |
        [{
          "title": "🚀 Deployment Successful",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "good",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{.app.metadata.labels.environment}}", "short": true},
            {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
            {"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true}
          ]
        }]
        
  template.app-health-degraded: |
    email:
      subject: 🚨 Application {{.app.metadata.name}} health degraded
    message: |
      ⚠️ **Health Alert!**
      
      **Application:** {{.app.metadata.name}}
      **Environment:** {{.app.metadata.labels.environment}}
      **Health Status:** {{.app.status.health.status}}
      **Health Message:** {{.app.status.health.message}}
      
      **Action Required:** Please check the application immediately.
      
      **Links:**
      - [ArgoCD App]({{.context.argocdUrl}}/applications/{{.app.metadata.name}})
      - [Kubernetes Dashboard](https://k8s-dashboard.local/#!/workloads?namespace={{.app.spec.destination.namespace}})
    slack:
      attachments: |
        [{
          "title": "🚨 Application Health Degraded",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "danger",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{.app.metadata.labels.environment}}", "short": true},
            {"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true},
            {"title": "Message", "value": "{{.app.status.health.message}}", "short": false}
          ]
        }]
        
  template.app-sync-failed: |
    email:
      subject: ❌ Application {{.app.metadata.name}} sync failed
    message: |
      🔴 **Sync Failed!**
      
      **Application:** {{.app.metadata.name}}
      **Environment:** {{.app.metadata.labels.environment}}
      **Sync Status:** {{.app.status.sync.status}}
      **Error Message:** {{.app.status.operationState.message}}
      
      **Action Required:** Check the sync operation and resolve the issue.
      
      **Links:**
      - [ArgoCD App]({{.context.argocdUrl}}/applications/{{.app.metadata.name}})
    slack:
      attachments: |
        [{
          "title": "❌ Sync Failed",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "danger",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{.app.metadata.labels.environment}}", "short": true},
            {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true}
          ]
        }]

  # Notification triggers
  trigger.on-deployed: |
    - description: Application is synced and healthy
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      
  trigger.on-health-degraded: |
    - description: Application has degraded health
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
      
  trigger.on-sync-failed: |
    - description: Application sync failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']

  # Service configuration (add your notification services)
  service.slack: |
    token: $slack-token
    
  service.email: |
    host: smtp.gmail.com
    port: 587
    from: argocd@company.com
    username: $email-username
    password: $email-password

  # Subscription configuration
  subscriptions: |
    # Week 5 Simple App notifications
    - recipients:
      - slack:simple-app-channel
      - email:dev-team@company.com
      triggers:
      - on-deployed
      - on-health-degraded  
      - on-sync-failed
      selector: app=simple-app