apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: simple-app-project
  namespace: argocd
  labels:
    project: simple-app
spec:
  description: Week 5 Simple App Project
  
  # Source repositories that applications in this project can pull from
  sourceRepos:
  - 'https://github.com/tamngo179/BT-PTUDDN.git'
  - 'https://github.com/tamngo179/*'
  
  # Destination clusters and namespaces that applications can deploy to
  destinations:
  - namespace: staging
    server: https://kubernetes.default.svc
  - namespace: production
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
    
  # Cluster resource allow list
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
    
  # Namespace resource allow list
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: ReplicaSet
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'policy'
    kind: PodDisruptionBudget
  - group: 'autoscaling'
    kind: HorizontalPodAutoscaler
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
    
  # Roles providing access to this project
  roles:
  - name: developer
    description: Developer access to staging
    policies:
    - p, proj:simple-app-project:developer, applications, get, simple-app-project/*, allow
    - p, proj:simple-app-project:developer, applications, sync, simple-app-project/simple-app-staging, allow
    - p, proj:simple-app-project:developer, applications, action/*, simple-app-project/simple-app-staging, allow
    groups:
    - developers
    - simple-app-devs
    
  - name: operator
    description: Operator access to all environments
    policies:
    - p, proj:simple-app-project:operator, applications, *, simple-app-project/*, allow
    - p, proj:simple-app-project:operator, repositories, *, *, allow
    groups:
    - operators
    - sre-team
    
  - name: viewer
    description: Read-only access
    policies:
    - p, proj:simple-app-project:viewer, applications, get, simple-app-project/*, allow
    groups:
    - viewers
    - stakeholders