apiVersion: v1
kind: ConfigMap
metadata:
  name: course-tracker-config
data:
  application.properties: |
    # H2 Database Configuration for Kubernetes
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=password
    
    # JPA/Hibernate Configuration
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.jpa.show-sql=true
    
    # H2 Console (for development)
    spring.h2.console.enabled=true
    spring.h2.console.path=/h2-console
    
    # Server Configuration
    server.port=8080
    
    # Kubernetes specific settings
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always