apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-tracker-deployment
  labels:
    app: course-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-tracker
  template:
    metadata:
      labels:
        app: course-tracker
    spec:
      containers:
      - name: course-tracker
        image: ghcr.io/tamngo179/course-tracker:latest
        imagePullPolicy: Always  # Use remote image
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30